In [6]:
import pandas as pd
import numpy as np
import seaborn as sns

In [7]:
import plotly.graph_objects as go

In [8]:
import funciones_laura as f

## 2006 a 2021 - MICRODATOS

### Tabla códigos tamaño municipios

In [9]:
cod_tamu = {1: 'Hasta 10.000 habitantes', 
            2: 'Municipio no capital de 10.001 a 20.000',
            3 : 'Municipio no capital de 20.001 a 50.000', 
            4: 'Municipio no capital de 50.001 a 100.000',      
            5: 'Municipio no capital  de más de 100.000',        
            6: 'Municipio capital de provincia'
            
           }
cod_tamu_invertido = {v: k for k, v in cod_tamu.items()}

### Tabla códigos provincias

In [10]:
cod_prov = pd.read_excel('./datos/MIGRACIONES/cod_prov.xlsx', header=1, names = ['CPRO', 'NOMBRE'])
cod_prov

    CPRO                  NOMBRE
0      1             Araba/Álava
1      2                Albacete
2      3        Alicante/Alacant
3      4                 Almería
4      5                   Ávila
5      6                 Badajoz
6      7          Balears, Illes
7      8               Barcelona
8      9                  Burgos
9     10                 Cáceres
10    11                   Cádiz
11    12      Castellón/Castelló
12    13             Ciudad Real
13    14                 Córdoba
14    15               Coruña, A
15    16                  Cuenca
16    17                  Girona
17    18                 Granada
18    19             Guadalajara
19    20                Gipuzkoa
20    21                  Huelva
21    22                  Huesca
22    23                    Jaén
23    24                    León
24    25                  Lleida
25    26               Rioja, La
26    27                    Lugo
27    28                  Madrid
28    29                  Málaga
29    30                  Murcia
30    31                 Navarra
31    32                 Ourense
32    33                Asturias
33    34                Palencia
34    35             Palmas, Las
35    36              Pontevedra
36    37               Salamanca
37    38  Santa Cruz de Tenerife
38    39               Cantabria
39    40                 Segovia
40    41                 Sevilla
41    42                   Soria
42    43               Tarragona
43    44                  Teruel
44    45                  Toledo
45    46       Valencia/València
46    47              Valladolid
47    48                 Bizkaia
48    49                  Zamora
49    50                Zaragoza
50    51                   Ceuta
51    52                 Melilla
52    66              Extranjero

In [11]:
# Creo diccionario con los códigos de provincias
dict_cod_prov = dict(zip(cod_prov['CPRO'], cod_prov['NOMBRE']))
dict_cod_prov

{1: 'Araba/Álava',
 2: 'Albacete',
 3: 'Alicante/Alacant',
 4: 'Almería',
 5: 'Ávila',
 6: 'Badajoz',
 7: 'Balears, Illes',
 8: 'Barcelona',
 9: 'Burgos',
 10: 'Cáceres',
 11: 'Cádiz',
 12: 'Castellón/Castelló',
 13: 'Ciudad Real',
 14: 'Córdoba',
 15: 'Coruña, A',
 16: 'Cuenca',
 17: 'Girona',
 18: 'Granada',
 19: 'Guadalajara',
 20: 'Gipuzkoa',
 21: 'Huelva',
 22: 'Huesca',
 23: 'Jaén',
 24: 'León',
 25: 'Lleida',
 26: 'Rioja, La',
 27: 'Lugo',
 28: 'Madrid',
 29: 'Málaga',
 30: 'Murcia',
 31: 'Navarra',
 32: 'Ourense',
 33: 'Asturias',
 34: 'Palencia',
 35: 'Palmas, Las',
 36: 'Pontevedra',
 37: 'Salamanca',
 38: 'Santa Cruz de Tenerife',
 39: 'Cantabria',
 40: 'Segovia',
 41: 'Sevilla',
 42: 'Soria',
 43: 'Tarragona',
 44: 'Teruel',
 45: 'Toledo',
 46: 'Valencia/València',
 47: 'Valladolid',
 48: 'Bizkaia',
 49: 'Zamora',
 50: 'Zaragoza',
 51: 'Ceuta',
 52: 'Melilla',
 66: 'Extranjero'}

### Tabla códigos municipios

In [12]:
# Tengo 52 hojas en el fichero de Excel que contiene los códigos de los municipios, una por cada municipio
cod_muni = pd.DataFrame()
for muni in range(52):
    cod_muni= pd.concat([cod_muni,pd.read_excel('./datos/MIGRACIONES/23codmun.xlsx', sheet_name=muni, header=2)], ignore_index=True)
cod_muni

      CPRO  CMUN  DC              NOMBRE
0        1    51   3  Agurain/Salvatierra
1        1     1   4     Alegría-Dulantzi
2        1     2   9              Amurrio
3        1    49   3                Añana
4        1     3   5              Aramaio
...    ...   ...  ..                  ...
8126    50   296   7            Zaida, La
8127    50   297   3             Zaragoza
8128    50   298   9                Zuera
8129    51     1   3                Ceuta
8130    52     1   8              Melilla

[8131 rows x 4 columns]

In [13]:
cod_muni.columns

Index(['CPRO', 'CMUN', 'DC', 'NOMBRE '], dtype='object')

In [14]:
# Elimino posibles espacios antes o después del nombre de las columnas
cod_muni.columns = list(map(lambda x: x.strip(),list(cod_muni.columns)))

In [15]:
# Los códigos de municipio completos con los que se trabajan habitualmente son
# la suma del código de provicia y el código de municipio de la tabla

In [16]:
# Creo una nueva columna con este código

cod_muni['CMUNICIPIO'] = cod_muni.apply(lambda x: f"{x['CPRO']:02}" + f"{x['CMUN']:03}", axis=1)
                                 
cod_muni

      CPRO  CMUN  DC               NOMBRE CMUNICIPIO
0        1    51   3  Agurain/Salvatierra      01051
1        1     1   4     Alegría-Dulantzi      01001
2        1     2   9              Amurrio      01002
3        1    49   3                Añana      01049
4        1     3   5              Aramaio      01003
...    ...   ...  ..                  ...        ...
8126    50   296   7            Zaida, La      50296
8127    50   297   3             Zaragoza      50297
8128    50   298   9                Zuera      50298
8129    51     1   3                Ceuta      51001
8130    52     1   8              Melilla      52001

[8131 rows x 5 columns]

In [20]:
cod_muni[cod_muni['CPRO']== 46]

      CPRO  CMUN  DC             NOMBRE CMUNICIPIO
6985    46     1   8             Ademuz      46001
6986    46     2   3               Ador      46002
6987    46     4   4           Agullent      46004
6988    46    42   5  Aielo de Malferit      46042
6989    46    43   1     Aielo de Rugat      46043
...    ...   ...  ..                ...        ...
7246    46   146   1             Xeresa      46146
7247    46   110   8          Xirivella      46110
7248    46   261   3             Yátova      46261
7249    46   262   8           Yesa, La      46262
7250    46   263   4              Zarra      46263

[266 rows x 5 columns]

In [13]:
# Añado una fila con el valor CPRO 66, CMUN 666 y CMUNICIPIO 66666 que corresponde a 'extranjero'
# y fila con valores 0 como descondocido

cod_muni.loc[len(cod_muni.index)] = [66, 6, 0, 'Extranjero', '66666']
cod_muni.loc[len(cod_muni.index)] = [0, 0, 0, 'Desconocido', '00000']
cod_muni

      CPRO  CMUN  DC               NOMBRE CMUNICIPIO
0        1    51   3  Agurain/Salvatierra      01051
1        1     1   4     Alegría-Dulantzi      01001
2        1     2   9              Amurrio      01002
3        1    49   3                Añana      01049
4        1     3   5              Aramaio      01003
...    ...   ...  ..                  ...        ...
8128    50   298   9                Zuera      50298
8129    51     1   3                Ceuta      51001
8130    52     1   8              Melilla      52001
8131    66     6   0           Extranjero      66666
8132     0     0   0          Desconocido      00000

[8133 rows x 5 columns]

## Tabla con longitud y latitud de municipios de España

In [4]:
long_lat_muni = pd.read_excel('listado-longitud-latitud-municipios-espana.xls', header=2)

long_lat_muni.drop(columns=['Altitud','Habitantes', 'Hombres', 'Mujeres'], inplace =True)
long_lat_muni

      Comunidad          Provincia  Población   Latitud  Longitud
0     Andalucía            Almería       Abla  37.14114 -2.780104
1     Andalucía            Almería   Abrucena  37.13305 -2.797098
2     Andalucía            Almería       Adra  36.74807 -3.022522
3     Andalucía            Almería  Albánchez  37.28710 -2.181163
4     Andalucía            Almería  Alboloduy  37.03319 -2.621750
...         ...                ...        ...       ...       ...
8107   Valencia  Valencia/València     Xeresa  39.00910 -0.217992
8108   Valencia  Valencia/València  Xirivella  39.46669 -0.427794
8109   Valencia  Valencia/València     Yátova  39.38500 -0.808174
8110   Valencia  Valencia/València  Yesa (La)  39.49916 -0.426125
8111   Valencia  Valencia/València      Zarra  39.09138 -1.075068

[8112 rows x 5 columns]

In [31]:
dict_lon = dict(zip(long_lat_muni['Población'], long_lat_muni['Longitud']))
dict_lat = dict(zip(long_lat_muni['Población'], long_lat_muni['Latitud']))

In [36]:
cod_muni['lat']=cod_muni['NOMBRE']
cod_muni['lon']=cod_muni['NOMBRE']

In [37]:
for k,v in dict_lat.items():
    cod_muni['lat'] = cod_muni['lat'].replace(k, v)
cod_muni

,CPRO,CMUN,DC,NOMBRE,CMUNICIPIO,lat,lon
0,1,51,3,Agurain/Salvatierra,01051,Agurain/Salvatierra,Agurain/Salvatierra
1,1,1,4,Alegría-Dulantzi,01001,42.84149,Alegría-Dulantzi
2,1,2,9,Amurrio,01002,43.05265,Amurrio
3,1,49,3,Añana,01049,42.80235,Añana
4,1,3,5,Aramaio,01003,43.054,Aramaio
...,...,...,...,...,...,...,...
8126,50,296,7,"Zaida, La",50296,"Zaida, La","Zaida, La"
8127,50,297,3,Zaragoza,50297,41.65629,Zaragoza
8128,50,298,9,Zuera,50298,41.86918,Zuera
8129,51,1,3,Ceuta,51001,35.88829,Ceuta
8130,52,1,8,Melilla,52001,35.29234,Melilla

In [38]:
for k,v in dict_lon.items():
    cod_muni['lon'] = cod_muni['lon'].replace(k, v)
cod_muni

,CPRO,CMUN,DC,NOMBRE,CMUNICIPIO,lat,lon
0,1,51,3,Agurain/Salvatierra,01051,Agurain/Salvatierra,Agurain/Salvatierra
1,1,1,4,Alegría-Dulantzi,01001,42.84149,-2.513507
2,1,2,9,Amurrio,01002,43.05265,-3.001022
3,1,49,3,Añana,01049,42.80235,-2.982607
4,1,3,5,Aramaio,01003,43.054,-2.566
...,...,...,...,...,...,...,...
8126,50,296,7,"Zaida, La",50296,"Zaida, La","Zaida, La"
8127,50,297,3,Zaragoza,50297,41.65629,-0.876538
8128,50,298,9,Zuera,50298,41.86918,-0.788164
8129,51,1,3,Ceuta,51001,35.88829,-5.316195
8130,52,1,8,Melilla,52001,35.29234,-2.938794

In [77]:
valor = [x  for x in cod_muni['lat'] if isinstance(x,str)]

In [78]:
valor

['Agurain/Salvatierra',
 'Arratzua-Ubarrundia',
 'Erriberabeitia',
 'Legutio',
 'Moreda de Álava/Moreda Araba',
 'Ballestero, El',
 'Bonillo, El',
 'Gineta, La',
 'Herrera, La',
 'Recueja, La',
 'Roda, La',
 'Alacant/Alicante',
 'Alcoi/Alcoy',
 'Alcosser',
 "Alfàs del Pi, l'",
 "Alqueria d'Asnar, l'",
 "Atzúbia, l'",
 'Beniardà',
 "Callosa d'en Sarrià",
 'Calp',
 'Camp de Mirra, el/Campo de Mirra',
 'Campello, el',
 'Castell de Guadalest, el',
 'Elx/Elche',
 'Fageca',
 'Fondó de les Neus, el/Hondón de las Nieves',
 'Monòver/Monóvar',
 'Montesinos, Los',
 'Nucia, la',
 "Orxa, l'/Lorcha",
 'Pinós, el/Pinoso',
 'Poble Nou de Benitatxell, el/Benitachell',
 'Poblets, els',
 "Ràfol d'Almúnia, el",
 'Romana, la',
 'Sant Vicent del Raspeig/San Vicente del Raspeig',
 'Torre de les Maçanes, la/Torremanzanas',
 "Vall d'Alcalà, la",
 'Vall de Gallinera, la',
 'Vall de Laguar, la',
 "Vall d'Ebo, la",
 'Verger, el',
 'Vila Joiosa, la/Villajoyosa',
 'Xàbia/Jávea',
 'Xixona/Jijona',
 'Albanchez',
 'Balanegra',
 'Ejido, El',
 'Gallardos, Los',
 'Íllar',
 'Mojonera, La',
 'Tres Villas, Las',
 'Adrada, La',
 'Aldehuela, La',
 'Arenal, El',
 'Barco de Ávila, El',
 'Barraco, El',
 'Berlanas, Las',
 'Bohodón, El',
 'Carrera, La',
 'Colilla, La',
 'Fresno, El',
 'Hija de Dios, La',
 'Horcajada, La',
 'Hornillo, El',
 'Hoyo de Pinares, El',
 'Llanos de Tormes, Los',
 'Losar del Barco, El',
 'Manjabálago y Ortigosa de Rioalmar',
 'Mirón, El',
 'Navas del Marqués, Las',
 'Oso, El',
 'Parral, El',
 'Serrada, La',
 'Tiemblo, El',
 'Torre, La',
 'Albuera, La',
 'Carrascalejo, El',
 'Codosera, La',
 'Coronada, La',
 'Garrovilla, La',
 'Guadiana',
 'Haba, La',
 'Lapa, La',
 'Morera, La',
 'Nava de Santiago, La',
 'Parra, La',
 'Roca de la Sierra, La',
 'Santos de Maimona, Los',
 'Zarza, La',
 'Castell, Es',
 'Deià',
 'Mercadal, Es',
 'Migjorn Gran, Es',
 'Pobla, Sa',
 'Salines, Ses',
 'Santa Eulària des Riu',
 "Ametlla del Vallès, L'",
 'Bigues i Riells del Fai',
 'Bruc, El',
 'Brull, El',
 'Cabanyes, Les',
 "Espunyola, L'",
 "Esquirol, L'",
 "Estany, L'",
 'Franqueses del Vallès, Les',
 'Garriga, La',
 'Granada, La',
 "Hospitalet de Llobregat, L'",
 'Hostalets de Pierola, Els',
 'Llacuna, La',
 'Llagosta, La',
 'Masies de Roda, Les',
 'Masies de Voltregà, Les',
 'Masnou, El',
 'Nou de Berguedà, La',
 'Palma de Cervelló, La',
 'Papiol, El',
 'Pla del Penedès, El',
 'Pobla de Claramunt, La',
 'Pobla de Lillet, La',
 'Pont de Vilomara i Rocafort, El',
 'Prat de Llobregat, El',
 'Prats de Rei, Els',
 'Quar, La',
 'Roca del Vallès, La',
 'Torre de Claramunt, La',
 'Altos, Los',
 'Ausines, Los',
 'Balbases, Los',
 'Barrios de Bureba, Los',
 'Castrillo Mota de Judíos',
 'Cueva de Roa, La',
 'Gallega, La',
 'Hormazas, Las',
 'Horra, La',
 'Puebla de Arganzón, La',
 'Quintanillas, Las',
 'Revilla y Ahedo, La',
 'Sequera de Haza, La',
 'Vid de Bureba, La',
 'Vid y Barrios, La',
 'Alagón del Río',
 'Aldea del Obispo, La',
 'Collado de la Vera',
 'Cumbre, La',
 'Garganta, La',
 'Gordo, El',
 'Granja, La',
 'Higuera de Albalat',
 'Pesga, La',
 'Pueblonuevo de Miramontes',
 'Tiétar',
 'Torno, El',
 'Vegaviana',
 'Barrios, Los',
 'Bosque, El',
 'Gastor, El',
 'Línea de la Concepción, La',
 'Medina Sidonia',
 'Puerto de Santa María, El',
 'San Martín del Tesorillo',
 "Alcora, l'",
 'Almassora',
 'Alqueries, les/Alquerías del Niño Perdido',
 'Ares del Maestrat',
 'Benassal',
 'Benicàssim/Benicasim',
 'Benlloc',
 'Castelló de la Plana',
 'Coves de Vinromà, les',
 'Herbers',
 'Jana, la',
 'Llosa, la',
 'Llucena/Lucena del Cid',
 'Mata de Morella, la',
 'Orpesa/Oropesa del Mar',
 'Pobla de Benifassà, la',
 'Pobla Tornesa, la',
 'Salzadella, la',
 'Serratella, la',
 'Suera/Sueras',
 'Toro, El',
 "Torre d'en Besora, la",
 "Torre d'en Doménec, la",
 'Useres, les/Useras',
 "Vall d'Uixó, la",
 'Vilafranca/Villafranca del Cid',
 'Vilavella, la',
 'Vistabella del Maestrat',
 'Xert',
 'Xodos/Chodos',
 'Cortijos, Los',
 'Labores, Las',
 'Pozuelos de Calatrava, Los',
 'Robledo, El',
 'Solana, La',
 'Blázquez, Los',
 'Carlota, La',
 'Carpio, El',
 'Fuente Carreteros',
 'Granjuela, La',
 'Guijarrosa, La',
 'Guijo, El',
 'Rambla, La',
 'Victoria, La',
 'Viso, El',
 'Baña, A',
 'Capela, A',
 'Coruña, A',
 'Laracha, A',
 'Oza-Cesuras',
 'Pino, O',
 'Pobra do Caramiñal, A',
 'Pontes de García Rodríguez, As',
 'Somozas, As',
 'Acebrón, El',
 'Alberca de Záncara, La',
 'Almarcha, La',
 'Arcas',
 'Cañavate, El',
 'Cierva, La',
 'Frontera, La',
 'Herrumblar, El',
 'Hinojosa, La',
 'Hinojosos, Los',
 'Hito, El',
 'Majadas, Las',
 'Mesas, Las',
 'Parra de las Vegas, La',
 'Pedernoso, El',
 'Pedroñeras, Las',
 'Peral, El',
 'Peraleja, La',
 'Pesquera, La',
 'Picazo, El',
 'Pozorrubio de Santiago',
 'Pozuelo, El',
 'Provencio, El',
 'Valdecolmenas, Los',
 'Valeras, Las',
 'Valle de Altomira, El',
 "Armentera, L'",
 "Bisbal d'Empordà, La",
 'Brunyola i Sant Martí Sapresa',
 'Calonge i Sant Antoni',
 'Cellera de Ter, La',
 "Escala, L'",
 "Far d'Empordà, El",
 'Jonquera, La',
 'Llosses, Les',
 'Pera, La',
 "Planes d'Hostoles, Les",
 'Port de la Selva, El',
 'Preses, Les',
 'Selva de Mar, La',
 "Tallada d'Empordà, La",
 'Vajol, La',
 'Vall de Bianya, La',
 "Vall d'en Bas, La",
 'Calahorra, La',
 'Dehesas Viejas',
 'Domingo Pérez de Granada',
 'Fornes',
 'Gabias, Las',
 'Guájares, Los',
 'Güéjar Sierra',
 'Íllora',
 'Ítrabo',
 'Játar',
 'Jérez del Marquesado',
 'Malahá, La',
 'Peza, La',
 'Pinar, El',
 'Taha, La',
 'Torrenueva Costa',
 'Valderrubio',
 'Valle, El',
 'Villa de Otura',
 'Zubia, La',
 'Bodera, La',
 'Cardoso de la Sierra, El',
 'Casar, El',
 'Cubillo de Uceda, El',
 'Huerce, La',
 'Inviernas, Las',
 'Mierla, La',
 'Miñosa, La',
 'Navas de Jadraque, Las',
 'Olivar, El',
 'Olmeda de Jadraque, La',
 'Ordial, El',
 'Pedregal, El',
 'Pobo de Dueñas, El',
 'Recuenco, El',
 'Sotillo, El',
 'Toba, La',
 'Yunta, La',
 'Bidania-Goiatz',
 'Donostia/San Sebastián',
 'Soraluze-Placencia de las Armas',
 'Almendro, El',
 'Campillo, El',
 'Cerro de Andévalo, El',
 'Granada de Río-Tinto, La',
 'Granado, El',
 'Marines, Los',
 'Nava, La',
 'Palma del Condado, La',
 'Zarza-Perrunal, La',
 'Beranuy',
 'Fueva, La',
 'Grado, El',
 'Peñas de Riglos, Las',
 'Puebla de Castro, La',
 'Pueyo de Araguás, El',
 'Sotonera, La',
 'Torla-Ordesa',
 'Carolina, La',
 'Espeluy',
 'Guardia de Jaén, La',
 'Iruela, La',
 'Puerta de Segura, La',
 'Torredelcampo',
 'Villares, Los',
 'Antigua, La',
 'Bañeza, La',
 'Barrios de Luna, Los',
 'Burgo Ranero, El',
 'Ercina, La',
 'Omañas, Las',
 'Pola de Gordón, La',
 'Robla, La',
 'Toral de los Vados',
 'Vecilla, La',
 'Alamús, Els',
 "Albagés, L'",
 "Albi, L'",
 'Avellanes i Santa Linya, Les',
 'Baronia de Rialb, La',
 'Bòrdes, Es',
 'Borges Blanques, Les',
 'Cogul, El',
 'Coma i la Pedra, La',
 "Espluga Calba, L'",
 'Floresta, La',
 'Fuliola, La',
 'Granadella, La',
 "Granja d'Escarp, La",
 "Guingueta d'Àneu, La",
 'Molsosa, La',
 'Oluges, Les',
 'Omellons, Els',
 'Omells de na Gaia, Els',
 "Palau d'Anglesola, El",
 'Plans de Sió, Els',
 'Poal, El',
 'Pobla de Cérvoles, La',
 'Pobla de Segur, La',
 'Pont de Bar, El',
 'Pont de Suert, El',
 'Portella, La',
 'Sentiu de Sió, La',
 "Seu d'Urgell, La",
 'Soleràs, El',
 'Torms, Els',
 'Torre de Cabdella, La',
 'Vall de Boí, La',
 "Valls d'Aguilar, Les",
 'Valls de Valira, Les',
 'Vansa i Fórnols, La',
 'Vilosell, El',
 'Lumbreras de Cameros',
 'Rasillo de Cameros, El',
 'Redal, El',
 'Villar de Arnedo, El',
 'Corgo, O',
 'Fonsagrada, A',
 'Incio, O',
 'Nogais, As',
 'Páramo, O',
 'Pastoriza, A',
 'Pobra do Brollón, A',
 'Pontenova, A',
 'Saviñao, O',
 'Valadouro, O',
 'Vicedo, O',
 'Acebeda, La',
 'Álamo, El',
 'Atazar, El',
 'Berrueco, El',
 'Boalo, El',
 'Cabrera, La',
 'Escorial, El',
 'Hiruela, La',
 'Horcajo de la Sierra-Aoslos',
 'Molar, El',
 'Molinos, Los',
 'Rozas de Madrid, Las',
 'Santos de la Humosa, Los',
 'Serna del Monte, La',
 'Vellón, El',
 'Borge, El',
 'Burgo, El',
 'Montecorto',
 'Serrato',
 'Villanueva de la Concepción',
 'Alcázares, Los',
 'Torres de Cotillas, Las',
 'Unión, La',
 'Abárzuza/Abartzuza',
 'Allín/Allin',
 'Ancín/Antzin',
 'Ansoáin/Antsoain',
 'Aranarache/Aranaratxe',
 'Arcos, Los',
 'Atez/Atetz',
 'Ayegui/Aiegi',
 'Barañáin/Barañain',
 'Bera',
 'Berrioplano/Berriobeiti',
 'Busto, El',
 'Cirauqui/Zirauki',
 'Ciriza/Ziritza',
 'Echarri/Etxarri',
 'Enériz/Eneritz',
 'Estella-Lizarra',
 'Etxarri Aranatz',
 'Gallipienzo/Galipentzu',
 'Guesálaz/Gesalatz',
 'Iza/Itza',
 'Juslapeña/Txulapain',
 'Leache/Leatxe',
 'Leoz/Leotz',
 'Lezaun',
 'Lizoain-Arriasgoiti/Lizoainibar-Arriasgoiti',
 'Mendigorria',
 'Monreal/Elo',
 'Navascués/Nabaskoze',
 'Oiz',
 'Olite/Erriberri',
 'Olóriz/Oloritz',
 'Orbaizeta',
 'Oroz-Betelu/Orotz-Betelu',
 'Peralta/Azkoien',
 'Pueyo/Puiu',
 'Romanzado/Erromantzatua',
 'Salinas de Oro/Jaitz',
 'Uharte Arakil',
 'Ujué/Uxue',
 'Unzué/Untzue',
 'Urroz',
 'Valle de Egüés/Eguesibar',
 'Valle de Ollo/Ollaran',
 'Zabalza/Zabaltza',
 'Arnoia, A',
 'Barco de Valdeorras, O',
 'Blancos, Os',
 'Bola, A',
 'Bolo, O',
 'Carballiño, O',
 'Gudiña, A',
 'Irixo, O',
 'Merca, A',
 'Mezquita, A',
 'Pereiro de Aguiar, O',
 'Peroxa, A',
 'Pobra de Trives, A',
 'Rúa, A',
 'Teixeira, A',
 'Veiga, A',
 'Franco, El',
 'Regueras, Las',
 'Pernía, La',
 'Puebla de Valdavia, La',
 'Serna, La',
 'Vid de Ojeda, La',
 'Aldea de San Nicolás, La',
 'Oliva, La',
 'Palmas de Gran Canaria, Las',
 'Cañiza, A',
 'Cerdedo-Cotobade',
 'Estrada, A',
 'Grove, O',
 'Guarda, A',
 'Illa de Arousa, A',
 'Lama, A',
 'Neves, As',
 'Porriño, O',
 'Rosal, O',
 'Alameda de Gardón, La',
 'Alamedilla, La',
 'Alberca, La',
 'Alberguería de Argañán, La',
 'Arco, El',
 'Atalaya, La',
 'Bastida, La',
 'Bodón, El',
 'Bouza, La',
 'Cabaco, El',
 'Cabeza de Béjar, La',
 'Calzada de Béjar, La',
 'Campo de Peñaranda, El',
 'Casas del Conde, Las',
 'Cerro, El',
 'Cubo de Don Sancho, El',
 'Éjeme',
 'Encina, La',
 'Fregeneda, La',
 'Fuente de San Esteban, La',
 'Hoya, La',
 'Maíllo, El',
 'Manzano, El',
 'Mata de Ledesma, La',
 'Maya, La',
 'Milano, El',
 'Orbada, La',
 'Payo, El',
 'Pedroso de la Armuña, El',
 'Peña, La',
 'Pino de Tormes, El',
 'Redonda, La',
 'Rinconada de la Sierra, La',
 'Sagrada, La',
 'Sahugo, El',
 'Santos, Los',
 'Sierpe, La',
 'Tala, La',
 'Tejado, El',
 'Tornadizo, El',
 'Veguillas, Las',
 'Vellés, La',
 'Vídola, La',
 'Zarza de Pumareda, La',
 'Guancha, La',
 'Llanos de Aridane, Los',
 'Matanza de Acentejo, La',
 'Orotava, La',
 'Paso, El',
 'Pinar de El Hierro, El',
 'Realejos, Los',
 'Rosario, El',
 'Sauzal, El',
 'Silos, Los',
 'Tanque, El',
 'Victoria de Acentejo, La',
 'Vilaflor de Chasna',
 'Astillero, El',
 'Corrales de Buelna, Los',
 'Rozas de Valdearroyo, Las',
 'Tojos, Los',
 'Carabias',
 'Espinar, El',
 'Huertos, Los',
 'Lastrilla, La',
 'Losa, La',
 'Matilla, La',
 'Real Sitio de San Ildefonso',
 'Algaba, La',
 'Cabezas de San Juan, Las',
 'Campana, La',
 'Castillo de las Guardas, El',
 'Coronil, El',
 'Corrales, Los',
 'Cuervo de Sevilla, El',
 'Garrobo, El',
 'Lantejuela',
 'Luisiana, La',
 'Madroño, El',
 'Molares, Los',
 'Navas de la Concepción, Las',
 'Palacios y Villafranca, Los',
 'Palmar de Troya, El',
 'Pedroso, El',
 'Puebla de Cazalla, La',
 'Puebla de los Infantes, La',
 'Puebla del Río, La',
 'Real de la Jara, El',
 'Rinconada, La',
 'Roda de Andalucía, La',
 'Ronquillo, El',
 'Rubio, El',
 'Saucejo, El',
 'Viso del Alcor, El',
 'Aldehuelas, Las',
 'Losilla, La',
 'Póveda de Soria, La',
 'Rábanos, Los',
 'Riba de Escalote, La',
 'Royo, El',
 'Villares de Soria, Los',
 "Albiol, L'",
 "Aldea, L'",
 "Aleixar, L'",
 "Ametlla de Mar, L'",
 "Ampolla, L'",
 "Arboç, L'",
 "Argentera, L'",
 'Bisbal de Falset, La',
 'Bisbal del Penedès, La',
 'Borges del Camp, Les',
 'Canonja, La',
 'Catllar, El',
 "Espluga de Francolí, L'",
 'Fatarella, La',
 'Febró, La',
 'Figuera, La',
 'Galera, La',
 'Garidells, Els',
 'Guiamets, Els',
 'Lloar, El',
 'Masó, La',
 'Masroig, El',
 'Milà, El',
 'Molar, El',
 'Montmell, El',
 'Morell, El',
 'Morera de Montsant, La',
 'Nou de Gaià, La',
 'Pallaresos, Els',
 "Palma d'Ebre, La",
 'Perelló, El',
 'Piles, Les',
 'Pinell de Brai, El',
 'Pla de Santa Maria, El',
 'Pobla de Mafumet, La',
 'Pobla de Massaluca, La',
 'Pobla de Montornès, La',
 "Pont d'Armentera, El",
 'Ràpita, La',
 'Riba, La',
 'Riera de Gaià, La',
 'Roda de Berà',
 'Rourell, El',
 'Secuita, La',
 'Selva del Camp, La',
 'Sénia, La',
 'Torre de Fontaubella, La',
 "Torre de l'Espanyol, La",
 'Vendrell, El',
 'Vilella Alta, La',
 'Vilella Baixa, La',
 'Cañada de Verich, La',
 'Castellar, El',
 'Cerollera, La',
 'Codoñera, La',
 'Cuba, La',
 'Cuervo, El',
 'Fresneda, La',
 'Ginebrosa, La',
 'Hoz de la Vieja, La',
 'Iglesuela del Cid, La',
 'Mata de los Olmos, La',
 'Olmos, Los',
 'Parras de Castellote, Las',
 'Pobo, El',
 'Portellada, La',
 'Puebla de Híjar, La',
 'Puebla de Valverde, La',
 'Vallecillo, El',
 'Zoma, La',
 'Campillo de la Jara, El',
 'Carpio de Tajo, El',
 'Casar de Escalona, El',
 'Cerralbos, Los',
 'Estrella, La',
 'Guardia, La',
 'Herencias, Las',
 'Iglesuela del Tiétar, La',
 'Mata, La',
 'Nava de Ricomalillo, La',
 'Navalmorales, Los',
 'Navalucillos, Los',
 'Puebla de Almoradiel, La',
 'Puebla de Montalbán, La',
 'Pueblanueva, La',
 'Puente del Arzobispo, El',
 'Real de San Vicente, El',
 'Romeral, El',
 'Toboso, El',
 'Torre de Esteban Hambrán, La',
 'Ventas con Peña Aguilera, Las',
 'Ventas de Retamosa, Las',
 'Ventas de San Julián, Las',
 'Villa de Don Fadrique, La',
 'Viso de San Juan, El',
 'Yébenes, Los',
 'Alboraia/Alboraya',
 "Alcúdia de Crespins, l'",
 "Alcúdia, l'",
 'Alfara de la Baronia',
 "Algímia d'Alfara",
 "Alqueria de la Comtessa, l'",
 'Benigànim',
 'Benissanó',
 'Benissuera',
 'Castelló',
 "Eliana, l'",
 "Énova, l'",
 'Font de la Figuera, la',
 "Font d'en Carròs, la",
 'Genovés, el',
 'Granja de la Costera, la',
 'Guadasséquies',
 'Llosa de Ranes, la',
 'Massalavés',
 'Moixent/Mogente',
 'Montroi/Montroy',
 'Nàquera/Náquera',
 'Novetlè/Novelé',
 "Olleria, l'",
 'Palomar, el',
 'Pobla de Farnals, la',
 'Pobla de Vallbona, la',
 'Pobla del Duc, la',
 'Pobla Llarga, la',
 'Potries',
 'Puig de Santa Maria, el',
 'Rafelbunyol',
 'Real',
 'Real de Gandia, el',
 'Ròtova',
 'Sagunt/Sagunto',
 'Sant Joanet',
 'València',
 'Vilallonga/Villalonga',
 'Yesa, La',
 'Campillo, El',
 'Mudarra, La',
 'Parrilla, La',
 'Pedraja de Portillo, La',
 'Seca, La',
 'Unión de Campos, La',
 'Zarza, La',
 'Arrankudiaga-Zollo',
 'Sopela',
 'Bóveda de Toro, La',
 'Corrales del Vino',
 'Cubo de Tierra del Vino, El',
 'Hiniesta, La',
 'Maderal, El',
 'Pego, El',
 'Perdigón, El',
 'Piñero, El',
 'Torre del Valle, La',
 'Almolda, La',
 'Almunia de Doña Godina, La',
 'Burgo de Ebro, El',
 'Buste, El',
 'Cuerlas, Las',
 'Fayos, Los',
 'Frago, El',
 'Frasno, El',
 'Jarque de Moncayo',
 'Joyosa, La',
 'Muela, La',
 'Pedrosas, Las',
 'Pintanos, Los',
 'Puebla de Alfindén, La',
 'Vilueña, La',
 'Zaida, La']

In [163]:
city = pd.read_csv('city.csv')

In [164]:
city.columns

Index(['objectId', 'muni', 'featureCode', 'countryCode', 'cityId', 'ACL',
       'name', 'population', 'updatedAt', 'location', 'country', 'createdAt',
       'adminCode', 'muniSub'],
      dtype='object')

In [165]:
muni_location = city.drop(columns=['objectId', 'featureCode', 'countryCode', 'cityId', 'ACL', 'population', 'updatedAt', 'country', 'createdAt',
       'adminCode', 'muniSub'])

In [166]:
muni_location['location'][1]

'{"__type":"GeoPoint","latitude":36.1369,"longitude":-5.84591}'

In [167]:
muni_location['lat'] = [x.split('latitude":')[1].split(',')[0] for x in muni_location['location']]
muni_location['long'] = [x.split('longitude":')[1].split('}')[0] for x in muni_location['location']]

In [173]:
muni_location[muni_location['muni'].isnull()]

Empty DataFrame
Columns: [muni, name, location, lat, long]
Index: []

In [172]:
muni_location.dropna(inplace=True)
muni_location

,muni,name,location,lat,long
0,6159.0,Zahinos,"{""__type"":""GeoPoint"",""latitude"":38.33135,""long...",38.33135,-6.95533
1,11007.0,Zahara de los Atunes,"{""__type"":""GeoPoint"",""latitude"":36.1369,""longi...",36.1369,-5.84591
2,18913.0,Zagra,"{""__type"":""GeoPoint"",""latitude"":37.25561,""long...",37.25561,-4.16905
3,18192.0,Zafarraya,"{""__type"":""GeoPoint"",""latitude"":36.97554,""long...",36.97554,-4.14442
4,4103.0,Zurgena,"{""__type"":""GeoPoint"",""latitude"":37.34218,""long...",37.34218,-2.03985
...,...,...,...,...,...
6908,8019.0,la Vila Olímpica del Poblenou,"{""__type"":""GeoPoint"",""latitude"":41.39074,""long...",41.39074,2.19679
6909,8019.0,la Verneda i la Pau,"{""__type"":""GeoPoint"",""latitude"":41.42399,""long...",41.42399,2.20304
6910,8019.0,Barri de Sant Andreu,"{""__type"":""GeoPoint"",""latitude"":41.43693,""long...",41.43693,2.19022
6911,34010.0,Rayaces,"{""__type"":""GeoPoint"",""latitude"":41.92137,""long...",41.92137,-4.71401
6912,31086.0,Sarriguren,"{""__type"":""GeoPoint"",""latitude"":42.81292,""long...",42.81292,-1.59815

In [174]:
muni_location['muni']=muni_location['muni'].apply(int)

In [175]:
muni_location

,muni,name,location,lat,long
0,6159,Zahinos,"{""__type"":""GeoPoint"",""latitude"":38.33135,""long...",38.33135,-6.95533
1,11007,Zahara de los Atunes,"{""__type"":""GeoPoint"",""latitude"":36.1369,""longi...",36.1369,-5.84591
2,18913,Zagra,"{""__type"":""GeoPoint"",""latitude"":37.25561,""long...",37.25561,-4.16905
3,18192,Zafarraya,"{""__type"":""GeoPoint"",""latitude"":36.97554,""long...",36.97554,-4.14442
4,4103,Zurgena,"{""__type"":""GeoPoint"",""latitude"":37.34218,""long...",37.34218,-2.03985
...,...,...,...,...,...
6908,8019,la Vila Olímpica del Poblenou,"{""__type"":""GeoPoint"",""latitude"":41.39074,""long...",41.39074,2.19679
6909,8019,la Verneda i la Pau,"{""__type"":""GeoPoint"",""latitude"":41.42399,""long...",41.42399,2.20304
6910,8019,Barri de Sant Andreu,"{""__type"":""GeoPoint"",""latitude"":41.43693,""long...",41.43693,2.19022
6911,34010,Rayaces,"{""__type"":""GeoPoint"",""latitude"":41.92137,""long...",41.92137,-4.71401
6912,31086,Sarriguren,"{""__type"":""GeoPoint"",""latitude"":42.81292,""long...",42.81292,-1.59815

In [44]:
cod_muni.isnull().sum()

CPRO          0
CMUN          0
DC            0
NOMBRE        0
CMUNICIPIO    0
lat           0
lon           0
dtype: int64

In [ ]:
Python
print (df3[df3.county.str.contains('Saint')])
1
print (df3[df3.county.str.contains('Saint')])

### Tabla de migraciones del 2006 al 2021

In [14]:
# descargo en una tabla todas las migraciones desde el año 2011 al 2021

migraciones = f.migrations_tables(2006, 2021)

migraciones

,SEXO,PROVNAC,EDAD,PROVALTA,MUNIALTA,ANOVAR,PROVBAJA,MUNIBAJA,TAMUALTA,TAMUBAJA
0,1,1,2,48,020,2006,1,,6,1
1,1,1,53,1,,2006,1,059,1,6
2,1,1,0,25,,2006,25,203,1,2
3,1,1,62,66,302,2006,1,059,,6
4,1,1,65,28,,2006,28,079,1,6
...,...,...,...,...,...,...,...,...,...,...
40996119,6,66,77,66,999,2021,52,001,,4
40996120,6,66,21,66,999,2021,52,001,,4
40996121,1,66,32,66,126,2021,52,001,,4
40996122,1,66,43,66,999,2021,52,001,,4
40996123,6,66,86,66,999,2021,52,001,,4

In [15]:
migraciones.head()

,SEXO,PROVNAC,EDAD,PROVALTA,MUNIALTA,ANOVAR,PROVBAJA,MUNIBAJA,TAMUALTA,TAMUBAJA
0,1,1,2,48,020,2006,1,,6,1
1,1,1,53,1,,2006,1,059,1,6
2,1,1,0,25,,2006,25,203,1,2
3,1,1,62,66,302,2006,1,059,,6
4,1,1,65,28,,2006,28,079,1,6

In [16]:
migraciones.dtypes

SEXO         int64
PROVNAC      int64
EDAD         int64
PROVALTA     int64
MUNIALTA    object
ANOVAR       int64
PROVBAJA     int64
MUNIBAJA    object
TAMUALTA    object
TAMUBAJA    object
dtype: object

In [17]:
# Se detectan varios valores de MUNIALTA y MUNIBAJA vacíos, se rellenan con un 0 como desconocido.
migraciones['MUNIALTA'].value_counts()

       7593628
079    2763518
999    2414215
019    1782977
666    1710526
        ...
440          1
512          1
209          1
513          1
514          1
Name: MUNIALTA, Length: 363, dtype: int64

In [18]:
migraciones['MUNIBAJA'].value_counts()

       6632918
079    2523057
999    1956304
019    1619753
128     721839
        ...
508          8
516          6
512          6
515          6
506          5
Name: MUNIBAJA, Length: 364, dtype: int64

In [19]:
null = migraciones['MUNIBAJA'].value_counts().index[0]
null

'   '

In [20]:
migraciones['MUNIBAJA'] = migraciones['MUNIBAJA'].replace(null,'000').apply(int)
migraciones['MUNIALTA'] = migraciones['MUNIALTA'].replace(null,'000').apply(int)
migraciones

,SEXO,PROVNAC,EDAD,PROVALTA,MUNIALTA,ANOVAR,PROVBAJA,MUNIBAJA,TAMUALTA,TAMUBAJA
0,1,1,2,48,20,2006,1,0,6,1
1,1,1,53,1,0,2006,1,59,1,6
2,1,1,0,25,0,2006,25,203,1,2
3,1,1,62,66,302,2006,1,59,,6
4,1,1,65,28,0,2006,28,79,1,6
...,...,...,...,...,...,...,...,...,...,...
40996119,6,66,77,66,999,2021,52,1,,4
40996120,6,66,21,66,999,2021,52,1,,4
40996121,1,66,32,66,126,2021,52,1,,4
40996122,1,66,43,66,999,2021,52,1,,4
40996123,6,66,86,66,999,2021,52,1,,4

In [21]:
migraciones[migraciones['PROVALTA']==66]['MUNIALTA'].value_counts()

999    2414215
666    1710526
125     167158
110     125835
126     116428
        ...
513          1
512          1
440          1
209          1
514          1
Name: MUNIALTA, Length: 202, dtype: int64

In [22]:
# Se detectan varios valores de TAMUALTA y TAMUBAJA vacíos que coinciden con provincia 66 que es extranjero.
migraciones['TAMUALTA'].value_counts()

6    10201005
1     7593628
3     6007341
      5647590
4     4147679
2     3947724
5     3451157
Name: TAMUALTA, dtype: int64

In [23]:
migraciones['TAMUBAJA'].value_counts()

     9504142
6    9478261
1    6632918
3    5186063
4    3620587
2    3380442
5    3193711
Name: TAMUBAJA, dtype: int64

In [24]:
null_ta = migraciones['TAMUBAJA'].value_counts().index[0]
null_ta

' '

In [25]:
migraciones[migraciones['TAMUALTA']== null_ta]['PROVALTA'].value_counts()

66    5647590
Name: PROVALTA, dtype: int64

In [26]:
migraciones[migraciones['TAMUBAJA']== null_ta]['PROVBAJA'].value_counts()

66    9504142
Name: PROVBAJA, dtype: int64

In [27]:
# Se detecta que cuando en PROVALTA y PROVBAJA se indica 66 (extranjero), hay varios códigos de municipio. 
# Se cambia a 666 extranjero

In [28]:
migraciones[migraciones['PROVBAJA']== 66]['MUNIBAJA'].value_counts()

999    1956304
128     708262
228     636287
343     470285
125     418048
        ...
130          7
512          6
516          6
515          6
506          5
Name: MUNIBAJA, Length: 203, dtype: int64

In [29]:
migraciones[migraciones['PROVALTA']== 66]['MUNIALTA'].value_counts()

999    2414215
666    1710526
125     167158
110     125835
126     116428
        ...
513          1
512          1
440          1
209          1
514          1
Name: MUNIALTA, Length: 202, dtype: int64

In [30]:
migraciones.loc[migraciones['PROVALTA']==66, 'MUNIALTA']  = 666

In [31]:
migraciones.loc[migraciones['PROVBAJA']==66, 'MUNIBAJA']  = 666

In [32]:
migraciones

,SEXO,PROVNAC,EDAD,PROVALTA,MUNIALTA,ANOVAR,PROVBAJA,MUNIBAJA,TAMUALTA,TAMUBAJA
0,1,1,2,48,20,2006,1,0,6,1
1,1,1,53,1,0,2006,1,59,1,6
2,1,1,0,25,0,2006,25,203,1,2
3,1,1,62,66,666,2006,1,59,,6
4,1,1,65,28,0,2006,28,79,1,6
...,...,...,...,...,...,...,...,...,...,...
40996119,6,66,77,66,666,2021,52,1,,4
40996120,6,66,21,66,666,2021,52,1,,4
40996121,1,66,32,66,666,2021,52,1,,4
40996122,1,66,43,66,666,2021,52,1,,4
40996123,6,66,86,66,666,2021,52,1,,4

In [33]:
#migraciones['MUNIALTA'] = migraciones['MUNIALTA'].apply(int)

In [34]:
#migraciones['MUNIBAJA'] = migraciones['MUNIBAJA'].apply(int)

In [35]:
migraciones['CODMUNIALTA'] = migraciones.apply(lambda x: f"{x['PROVALTA']:02}" + f"{x['MUNIALTA']:03}", axis=1)

In [36]:
migraciones['CODMUNIBAJA'] = migraciones.apply(lambda x: f"{x['PROVBAJA']:02}" + f"{x['MUNIBAJA']:03}", axis=1)

In [37]:
migraciones

,SEXO,PROVNAC,EDAD,PROVALTA,MUNIALTA,ANOVAR,PROVBAJA,MUNIBAJA,TAMUALTA,TAMUBAJA,CODMUNIALTA,CODMUNIBAJA
0,1,1,2,48,20,2006,1,0,6,1,48020,01000
1,1,1,53,1,0,2006,1,59,1,6,01000,01059
2,1,1,0,25,0,2006,25,203,1,2,25000,25203
3,1,1,62,66,666,2006,1,59,,6,66666,01059
4,1,1,65,28,0,2006,28,79,1,6,28000,28079
...,...,...,...,...,...,...,...,...,...,...,...,...
40996119,6,66,77,66,666,2021,52,1,,4,66666,52001
40996120,6,66,21,66,666,2021,52,1,,4,66666,52001
40996121,1,66,32,66,666,2021,52,1,,4,66666,52001
40996122,1,66,43,66,666,2021,52,1,,4,66666,52001
40996123,6,66,86,66,666,2021,52,1,,4,66666,52001

In [38]:
migraciones.dtypes

SEXO            int64
PROVNAC         int64
EDAD            int64
PROVALTA        int64
MUNIALTA        int64
ANOVAR          int64
PROVBAJA        int64
MUNIBAJA        int64
TAMUALTA       object
TAMUBAJA       object
CODMUNIALTA    object
CODMUNIBAJA    object
dtype: object

In [39]:
# Exporto las tablas a ficheros .csv para poder utilizar en otro notebook
migraciones.to_csv('migraciones_2006_2021.csv')

In [40]:
cod_muni.to_csv('cod_muni.csv')

In [41]:
cod_prov.to_csv('cod_prov.csv')